version: "3.9"
services:
  algspec-ui:
    build: "./algspec-ui/"
    ports: 
      - "8081:80"
  algspec-api:
    build: 
      context: "./api/"
      args:
        - DB_URI=${DB_URI}
    ports: 
      - "8080:8080"