version: "3.9"
services:
  algspec-ui:
    build: 
      context: "./algspec-ui/"
      args:
        - BASE_API_URL=${BASE_API_URL}
    ports: 
      - "8081:80"
  algspec-api:
    build: 
      context: "./api/"
      args:
        - DB_URI=${DB_URI}
        - SESSION_SECRET=${SESSION_SECRET}
    ports: 
      - "8080:8080"